name: Customies
description: A PocketMine-MP plugin that implements support for custom blocks, items and entities.

main: customiesdevs\customies\Customies
src-namespace-prefix: customiesdevs\customies
<<<<<<< HEAD
version: 1.4.0
=======
version: 1.3.5
>>>>>>> ac89c78b7464f3b7f83d2f0c8d9a26ff6623d9b3
api: 5.25.0

authors:
  - DenielWorld
  - TwistedAsylumMC
contributors:
  - JackNoordhuis
  - Unickorn
  - abimek
