name: Customies
description: A PocketMine-MP plugin that implements support for custom blocks, items and entities.

main: twistedasylummc\customies\Customies
src-namespace-prefix: twistedasylummc\customies
version: 1.0.3
api: 4.0.0

authors:
  - DenielWorld
  - TwistedAsylumMC
contributors:
  - JackNoordhuis
  - Unickorn
